---
spring:
  profiles: test | spring | default | dev | prod

no.nav.security.jwt:
  expirythreshold: ${EXPIRYTHRESHOLD} #threshold in minutes until token expires
  issuer.someshortname:
    discoveryurl: ${DISCOVERYURL}
    accepted_audience: ${ACCEPTED_AUDIENCE}
    cookie_name: ${COOKIE_NAME}

  client:
    registration:
      soknadsarkiverer:
        token-endpoint-url: ${TOKEN-ENDPOINT-URL}
        grant-type: ${GRANT-TYPE}
        scope: openid
        authentication:
          client-id: ${CLIENT-ID}
          client-secret: ${CLIENT-SECRET}
          client-auth-method: ${CLIENT-AUTH-METHOD}
