apiVersion: "monitoring.coreos.com/v1"
kind: PrometheusRule
metadata:
  labels:
    team: team-soknad
  name: soknadsarkiverer-alerts
  namespace: team-soknad
spec:
  groups:
    - name: {{ env-name }}
      rules:
        - alert: Low number of soknadsarkiverer pods
          expr: count(kube_pod_container_status_running{container="soknadsarkiverer", namespace=~"team-soknad"}) < {{ number_of_pods }}
          for: 5m
          annotations:
            title: "Low number of soknadsarkiverer instances running"
            consequence: "There can be different causes for this, check logs for cause and evaluation of consequences."
            action: {{ error_log_url }}
            summary: "Service has reported less than {{number_of_pods}} running PODs within 5 minutes."
            sla: "Action should be taken as soon as possible"
          labels:
            service: "soknadsarkiverer"
            namespace: fyllut-sendinn
            special_type_to_use_in_alertmanager_config: {{common-labels.special_type_to_use_in_alertmanager_config}}
            alert_type: custom
            severity: warning
