apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "320M"
  name: {{appname}}
  namespace: team-soknad
  labels:
    team: team-soknad
spec:
  image: {{image}}
  port: 8091
  liveness:
    path: /internal/isAlive
    initialDelay: 100
    failureThreshold: 10
    timeout: 20
  readiness:
    path: /internal/isReady
    initialDelay: 100
    timeout: 20
  preStopHookPath: /internal/stop
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: {{replicas-min}}
    max: {{replicas-max}}
  resources:
    limits:
      cpu: 3000m
      memory: 8Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  ingresses:
    - {{ingress}}
  kafka:
    pool: {{kafka-pool}}
    streams: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: soknadsadmins
    outbound:
      rules:
      {{#each outbound}}
        - application: "{{this}}"
      {{/each}}
  envFrom:
    - secret: soknadsarkiver-google-secret
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
    - secret: shared-innsending-secret
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{profile}}
    - name: DELAY_BEFORE_KAFKA_INITIALIZATION
      value: "5"
    - name: BOOTSTRAPPING_TIMEOUT
      value: "0"
    - name: KAFKA_SECURITY
      value: "TRUE"
    - name: KAFKA_MAIN_TOPIC
      value: {{kafka-main-topic}}
    - name: KAFKA_PROCESSING_TOPIC
      value: {{kafka-processingeventlog-topic}}
    - name: KAFKA_MESSAGE_TOPIC
      value: {{kafka-message-topic}}
    - name: KAFKA_METRICS_TOPIC
      value: {{kafka-metrics-topic}}
    - name: FILESTORAGE_HOST
      value: {{filestorage-host}}
    - name: JOARK_HOST
      value: {{joark-host}}
    - name: DOKARKIV_SCOPE
      value: {{dokarkiv-scope}}
    - name: SOKNADSFILLAGER_SCOPE
      value: {{soknadsfillager-scope}}
    - name: SEND_TO_JOARK
      value: "{{send-to-joark}}"
