apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: soknadsarkiverer
  namespace: q0
  labels:
    team: team-soknad
spec:
  image: {{image}}
  port: 8091
  liveliness:
    path: /internal/isAlive
    initialDelay: 20
    failureThreshold: 10
    timeout: 1
  readiness:
    path: /internal/isAlive
    initialDelay: 20
    timeout: 1
  prometheus:
    enable: true
    path: /metrics
  replicas:
    min: 2
    max: 4
  resource:
    limits:
      cpu: 3000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://soknadsarkiverer-q0.nais.preprod.local"
    - "https://soknadsarkiverer-q0.dev-fss.nais.io"
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/dev/srvsoknadsarkiverer
      - mountPath: /var/run/secrets/nais.io/kv
        kvPath: /kv/preprod/fss/soknadsarkiverer/default
      - mountPath: /var/run/secrets/nais.io/appdynamics
        kvPath: /apikey/appdynamics/dev

  env:
    - name: APP_VERSION
      value: {{ app_version }}
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: SCHEMA_REGISTRY_URL
      value: https://kafka-schema-registry.nais.preprod.local
    - name: KAFKA_SECURITY
      value: 'TRUE'
    - name: KAFKA_SECPROT
      value: SASL_SSL
    - name: KAFKA_SASLMEC
      value: PLAIN
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: KAFKA_INPUT_TOPIC
      value: privat-soknadInnsendt-v1-q0
    - name: KAFKA_PROCESSING_TOPIC
      value: privat-soknadInnsendt-processingEventLog-v1-q0
    - name: KAFKA_MESSAGE_TOPIC
      value: privat-soknadInnsendt-messages-v1-q0
