apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: soknadsarkiverer
  namespace: default
  labels:
    team: team-soknad
spec:
  image: {{image}}
  port: 8091
  liveliness:
    path: /internal/isAlive
    initialDelay: 100
    failureThreshold: 10
    timeout: 20
  readiness:
    path: /internal/isAlive
    initialDelay: 100
    timeout: 20
  prometheus:
    enable: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resource:
    limits:
      cpu: 3000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - "https://soknadsarkiverer.nais.preprod.local"
    - "https://soknadsarkiverer.dev-fss.nais.io"
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/dev/srvsoknadarkiverer
      - mountPath: /var/run/secrets/nais.io/kv
        kvPath: /kv/preprod/fss/soknadsarkiverer/default
      - mountPath: /var/run/secrets/nais.io/appdynamics
        kvPath: /apikey/appdynamics/dev


  env:
    - name: APP_VERSION
      value: {{ app_version }}
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: SCHEMA_REGISTRY_URL
      value: https://kafka-schema-registry.nais.preprod.local
    - name: KAFKA_SECURITY
      value: 'TRUE'
    - name: KAFKA_SECPROT
      value: SASL_SSL
    - name: KAFKA_SASLMEC
      value: PLAIN
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: KAFKA_INPUT_TOPIC
      value: privat-soknadInnsendt-v1-default
    - name: KAFKA_PROCESSING_TOPIC
      value: privat-soknadInnsendt-processingEventLog-v1-default
    - name: KAFKA_MESSAGE_TOPIC
      value: privat-soknadInnsendt-messages-v1-default
    - name: FILESTORAGE_HOST
      value: https://tjenester-default.nav.no/soknadsfillager
    - name: TOKENENDPOINTURL
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token
    - name: GRANTTYPE
      value: client_credentials
    - name: SCOPE
      value: openid
    - name: CLIENTID
      value: 7b9e459e-225f-4fa8-b79f-2a15b993dae8
    - name: CLIENTAUTHMETHOD
      value: client_secret_basic
    - name: ACCEPTEDAUDIENCE
      value: 7b9e459e-225f-4fa8-b79f-2a15b993dae8
    - name: COOKIENAME
      value: soknadsarkiverer-idtoken
    - name: DISCOVERYURL
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
    - name: JOARK_HOST
      value: https://dokarkiv-q0.nais.preprod.local

