apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: soknadsarkiverer
  namespace: q1
  labels:
    team: team-soknad
spec:
  image: {{image}}
  port: 8090
  liveliness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  prometheus:
    enable: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resource:
    limits:
      cpu: 3000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://tjenester-q1.nav.no/soknadsarkiverer"
    - "https://soknadsarkiverer-q1.nais.oera-q.local/"
  vault:
    enabled: true
    paths:
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/appdynamics
  env:
    - name: APP_VERSION
      value: {{ app_version }}
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: KAFKA_CLIENTID
      value: srvsoknadsarkiverer
    - name: KAFKA_SECURITY
      value: 'TRUE'
    - name: KAFKA_SECPROT
      value: SASL_SSL
    - name: KAFKA_SASLMEC
      value: PLAIN
    - name: KAFKA_TOPIC
      value: privat-soknadInnsendt-v1-q1
    - name: SRVSSOKNADSARKIVERER_USERNAME
      value: srvsoknadarkiverer
    - name: APPLICATION_PROFILE
      value: dev
