apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: soknadsarkiverer
  namespace: q1
  labels:
    team: team-soknad
spec:
  image: {{image}}
  port: 8091
  liveliness:
    path: /internal/isAlive
    initialDelay: 100
    failureThreshold: 10
    timeout: 20
  readiness:
    path: /internal/isReady
    initialDelay: 100
    timeout: 20
  preStopHookPath: /internal/stop
  prometheus:
    enable: true
    path: /internal/prometheus
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 3000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 1024Mi
  ingresses:
    - "https://soknadsarkiverer-q1.dev.adeo.no"
  accessPolicy:
    inbound:
      rules:
        - application: soknadsadmins
    outbound:
      rules:
        - application: soknadsfillager
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/dev/srvsoknadarkiverer
      - mountPath: /var/run/secrets/nais.io/kv
        kvPath: /kv/preprod/fss/soknadsarkiverer/default
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/preprod/fss/soknadsarkiverer/environment
      - mountPath: /var/run/secrets/nais.io/appdynamics
        kvPath: /apikey/appdynamics/dev

  env:
    - name: APP_VERSION
      value: {{ app_version }}
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: SCHEMA_REGISTRY_URL
      value: https://kafka-schema-registry.nais.preprod.local
    - name: KAFKA_SECURITY
      value: 'TRUE'
    - name: KAFKA_SECPROT
      value: SASL_SSL
    - name: KAFKA_SASLMEC
      value: PLAIN
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: KAFKA_INPUT_TOPIC
      value: privat-soknadInnsendt-v1-q1
    - name: KAFKA_PROCESSING_TOPIC
      value: privat-soknadInnsendt-processingEventLog-v1-q1
    - name: KAFKA_MESSAGE_TOPIC
      value: privat-soknadInnsendt-messages-v1-q1
    - name: FILESTORAGE_HOST
      value: https://soknadsfillager-q1.dev.adeo.no
    - name: JOARK_HOST
      value: https://dokarkiv-q1.dev.adeo.no
