server:
  port: 8091

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  kafka:
    streams:
      application-id: soknadsarkiverer

application:
  kafka-bootstrap-servers: localhost:9092
  kafka-topic: privat-soknadInnsendt-sendsoknad-v1-q0
  joark-host: http://localhost:8092
  joark-url: /joark/save



---
spring:
  profiles: docker

application:
  kafka-bootstrap-servers: kafka-broker:29092
  joark-host: http://joark-mock:8092
