server:
  port: 8091

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics
    base-path: "/internal"
    path-mapping:
      info: "/isAlive"
  metrics:
    export:
      prometheus:
        enabled: true

---
spring:
  profiles: test

no.nav.security.jwt:
  issuer:
    someshortname:
      discoveryurl: http://metadata
      accepted_audience: aud-localhost
      cookie_name: localhost-idtoken
    azuread:
      discoveryurl: http://metadata
      accepted_audience: aud-localhost
      cookie_name: localhost-idtoken

  client:
    registration:
      soknadsarkiverer:
        token-endpoint-url: http://localhost:8181/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: scope1
        authentication:
          client-id: testclient
          client-secret: testsecret
          client-auth-method: client_secret_basic

---
spring:
  profiles: spring | default | docker | dev | prod

no.nav.security.jwt:
  expirythreshold: ${EXPIRYTHRESHOLD} #threshold in minutes until token expires

  issuers: isso, azureread
  issuer:
    isso:
      discoveryurl: ${DISCOVERYURL}
      accepted_audience: ${ACCEPTEDAUDIENCE}
      cookie_name: ${COOKIENAME}
    azureread:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}

  client:
    registration:
      soknadsarkiverer:
        token-endpoint-url: ${TOKENENDPOINTURL}
        grant-type: ${GRANTTYPE}
        scope: ${SCOPE}
        authentication:
          client-id: ${CLIENTID}
          client-secret: ${CLIENTSECRET}
          client-auth-method: ${CLIENTAUTHMETHOD}
      onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: https://graph.microsoft.com/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic

