server:
  port: 8091

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: soknadsarkiverer
    streams:
      application-id: soknadsarkiverer

application:
  kafka-topic: privat-soknadInnsendt-sendsoknad-v1-q0
  joark-host: http://localhost:8092
  joark-url: /joark/save



---
spring:
  profiles: docker
  kafka:
    bootstrap-servers: kafka-broker:29092

application:
  joark-host: http://joark-mock:8092
