server:
  port: 8091

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics
    base-path: "/internal"
    path-mapping:
      info: "/isAlive"
  metrics:
    export:
      prometheus:
        enabled: true

http.proxy.parametername: notused

no.nav.security.jwt:
  expirythreshold: 1 #threshold in minutes until token expires
  issuer.someshortname:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken
