server:
  port: 8091

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  kafka:
    consumer:
      group-id: myGroup
    streams:
      application-id: apabepa
    bootstrap-servers: localhost:9092

application:
  joark-url: "/joark/save"
  joark-host: "http://localhost:8092"
  kafka:
    bootstrap-servers: localhost:9092



---
spring:
  profiles: docker
  kafka:
    bootstrap-servers: kafka-broker:29092

application:
  joark-host: "http://joark-mock:8092"
  kafka:
    bootstrap-servers: kafka-broker:29092



---
spring:
  profiles: test
  kafka:
    listener:
      missing-topics-fatal: false
