server:
  port: 8091

management:
  endpoints:
    web:
      exposure:
        include: "*"

application:
  kafka-bootstrap-servers: localhost:9092

  kafka-topic: privat-soknadInnsendt-sendsoknad-v1-q0
  kafka-retry-topic: privat-retry-soknadInnsendt-sendsoknad-v1-q0
  kafka-dead-letter-topic: privat-dlq-soknadInnsendt-sendsoknad-v1-q0

  kafka-max-retry-count: 20

  joark-host: http://localhost:8092
  joark-url: /joark/save

  filestorage-host: http://localhost:9042
  filestorage-url: /filer?uuids=



---
spring:
  profiles: docker

application:
  kafka-bootstrap-servers: kafka-broker:29092
  joark-host: http://joark-mock:8092
  filestorage-host: http://soknadsfillager:9042
