kafka:
  applicationId: end-to-end
  bootstrappingTimeout: 60
  security:
    enabled: FALSE
  topics:
    mainTopic: privat-soknadinnsending-v1-dev
    processingTopic: privat-soknadinnsending-processingeventlog-v1-dev
    messageTopic: privat-soknadinnsending-messages-v1-dev
    arkiveringstilbakemeldingTopic: soknadinnsending-arkiveringstilbakemelding-dev
    metricsTopic: privat-soknadinnsending-metrics-v1-dev
services:
  tasklist:
    scheduling:
      startUpSeconds: 8
      secondsBetweenRetries: [0, 1, 1, 1, 1, 1]
no.nav.security:
  jwt:
    issuer.azuread:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}
    client:
      registration:
        soknadsfillager:
          token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
          grant-type: client_credentials
          scope: ${SOKNADSFILLAGER_SCOPE}
          authentication:
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            client-auth-method: client_secret_basic
        innsendingApi:
          token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
          grant-type: client_credentials
          scope: ${INNSENDING_API_SCOPE}
          authentication:
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            client-auth-method: client_secret_basic
        arkiv:
          token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
          grant-type: client_credentials
          scope: ${DOKARKIV_SCOPE}
          authentication:
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            client-auth-method: client_secret_basic
        saf-maskintilmaskin:
          token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
          grant-type: client_credentials
          scope: ${SAF_SCOPE}
          authentication:
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            client-auth-method: client_secret_basic

joark:
  host: ${JOARK_HOST}
  sendToJoark: true
  journal-post: /rest/journalpostapi/v1/journalpost
filestorage:
  host: ${FILESTORAGE_HOST}
  files: /files/
innsendingapi:
  host: ${INNSENDING_API_HOST}
saf:
  url: ${SAF_URL}
  path: /graphql
applicationName: "soknadsarkiverer"
status_log_url: "https://logs.adeo.no"

