kafka:
  applicationId: end-to-end
  bootstrappingTimeout: 60
  security:
    enabled: FALSE
  topics:
    mainTopic: privat-soknadinnsending-v1-dev
    processingTopic: privat-soknadinnsending-processingeventlog-v1-dev
    messageTopic: privat-soknadinnsending-messages-v1-dev
    metricsTopic: privat-soknadinnsending-metrics-v1-dev
services:
  tasklist:
    scheduling:
      startUpSeconds: 8
      secondsBetweenRetries: [0, 1, 1, 1, 1, 1]
no.nav.security:
  basic:
    username: admin
    password: password
  jwt:
    issuer.azuread:
      discoveryurl: http://metadata
      accepted_audience: aud-localhost
      cookie_name: localhost-idtoken
    client:
      registration:
        soknadsfillager:
          token-endpoint-url: http://localhost:8181/oauth2/v2.0/token
          grant-type: client_credentials
          scope: scope1
          authentication:
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            client-auth-method: client_secret_basic
        innsendingApi:
          token-endpoint-url: http://localhost:8181/oauth2/v2.0/token
          grant-type: client_credentials
          scope: scope1
          authentication:
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            client-auth-method: client_secret_basic
        arkiv:
          token-endpoint-url: http://localhost:8181/oauth2/v2.0/token
          grant-type: client_credentials
          scope: scope1
          authentication:
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            client-auth-method: client_secret_basic
        saf-maskintilmaskin:
          token-endpoint-url: http://localhost:8181/oauth2/v2.0/token
          grant-type: client_credentials
          scope: scope1
          authentication:
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            client-auth-method: client_secret_basic

joark:
  host: ${JOARK_HOST}
  sendToJoark: true
  journal-post: /rest/journalpostapi/v1/journalpost
filestorage:
  host: ${FILESTORAGE_HOST}
  files: /files/
  username: sender
  password: password
innsendingapi:
  host: ${INNSENDING_API_HOST}
saf:
  url: ${SAF_URL}
  path: /graphql
applicationName: "soknadsarkiverer"


