apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-soknadinnsending-metrics-v1
  namespace: team-soknad
  labels:
    team: team-soknad
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 72
  acl:
    - team: team-soknad
      application: soknadsmottaker
      access: readwrite
    - team: team-soknad
      application: soknadsarkiverer
      access: readwrite
